
version: '3.8'
services:
  grafana:
    image: 'grafana/grafana-oss'
    restart: unless-stopped
    hostname: 'grafana'
    container_name: 'grafana'
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    # command: 
    #   - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '3000:3000'
    volumes:
      - '$GRAF_HOMEDIR/graf-pdata/grafana:/var/lib/grafana'

networks:
  graf-n:
    name: graf-network

volumes:
  graf-v:
    name: graf-data